#!/bin/sh

QMAILDIR=$(getent passwd qmaild | cut -d: -f6)
QMAILDUID=`id -u vpopmail`
NOFILESGID=`id -g vpopmail`
MAXSMTPD=`cat $QMAILDIR/control/concurrencyincoming`
SOFTLIMIT=`cat $QMAILDIR/control/softlimit`
LOCAL=`head -1 $QMAILDIR/control/me`
TCPRULES_DIR=$QMAILDIR/control

SSL_DIR=$QMAILDIR/control
SSL_CHROOT=$SSL_DIR
SSL_UID=$QMAILDUID
SSL_GID=$NOFILESGID
CERTFILE=$SSL_DIR/servercert.pem
KEYFILE=$SSL_DIR/servercert.pem
DHFILE=$SSL_DIR/dh4096.pem
export SSL_UID SSL_GID SSL_CHROOT
export CERTFILE KEYFILE DHFILE

#export ALLOW_BARELF=1
#export REJECTNULLSENDERS=1
export SMTPAUTH="!"

# enable greetdelay for qmail-smtpd
export SMTPD_GREETDELAY=3
export DROP_PRE_GREET=1

# enable chkuser
export CHKUSER_START=ALWAYS

# turn off TLS on port 465
export FORCETLS=0
export DISABLETLS=1

# require that authenticated user and 'mail from' are identical
export FORCEAUTHMAILFROM="1"

# rcptcheck-overlimit. Limits the number of emails sent by relayclients
if [ -x $QMAILDIR/bin/rcptcheck-overlimit ]; then
  export RCPTCHECK=$QMAILDIR/bin/rcptcheck-overlimit
  export RCPTCHECKRELAYCLIENT="1"
fi

exec /usr/local/bin/softlimit -m "$SOFTLIMIT" \
    /usr/local/bin/sslserver -seV -Rp -l "$LOCAL" \
    -Xx ${TCPRULES_DIR}/tcp.smtp.cdb -c "$MAXSMTPD" \
    -u "$QMAILDUID" -g "$NOFILESGID" 0 smtps \
    $QMAILDIR/bin/qmail-smtpd ~vpopmail/bin/vchkpw /bin/true 2>&1

# /usr/local/bin/recordio \
# $QMAILDIR/bin/jgreylist \
# $QMAILDIR/bin/qmail-smtpd /bin/true 2>&1
