#!/bin/sh
#
# mlcat
# cat frontend for multilog files
# Klaus Reimer <k@ailis.de>

TITLE=mlcat
VERSION=0.6
AUTHOR="Klaus Reimer"
EMAIL=k@ailis.de
COPYRIGHT="Copyright (C) 2000-2011 by $AUTHOR"

showHelp() {
  echo "Usage: $TITLE [OPTION]... SERVICE [CAT-OPTION]..."
  echo "cat frontend for multilog files"
  echo ""
  echo "  -h, --help     Display help and exit"
  echo "  -V, --version  Display version and exit"
  echo ""
  echo "This utility is a frontend for cat to easily cat logfiles"
  echo "from services running under daemontools. Simply specify the service"
  echo "name (wich is the name of the service directory without leading path)."
  echo "You can specify any cat options after the service name. See the man"
  echo "page for cat for more infos."
  echo ""
  echo "Report bugs to $AUTHOR <$EMAIL>"
}

showVersion() {
  echo "$TITLE $VERSION"
  echo ""
  echo "$COPYRIGHT"
  echo "This is free software; you can redistribute it and/or modify it under"
  echo "the terms of the GNU General Public License as published by the Free"
  echo "Software Foundation; either version 2 of the License, or (at your"
  echo "option) any later version."
}

while getopts "hV-:" NAME
do
  case "$NAME" in
    h)
      showHelp
      exit 0
      ;;
    V)
      showVersion
      exit 0
      ;;
    -)
      case "$OPTARG" in
        help)
          showHelp
          exit 0
          ;;
        version)
          showVersion
          exit 0
          ;;
        *)
          echo "Unknown option: $OPTARG"
          showHelp
          exit 1
      esac  
      ;;
    *)
      echo "Unknown option: $OPTARG"
      showHelp
      exit 1
  esac
done

shift `expr $OPTIND - 1`

if [ $# -eq 0 ]
then
  showHelp
  exit 1
fi

if ! SVDIR=`svdir 2>&1`
then
  echo "$TITLE: $SVDIR" >&2
  exit 1
fi

SERVICE=$1

shift 1

if [ -d $SVDIR/$SERVICE/ ]; then
	svok $SVDIR/qmail-$SERVICE || exit 1
	svok $SVDIR/qmail-$SERVICE/log || exit 1
	cat /var/log/qmail/$SERVICE/current $* | tai64nlocal
else
	svok $SVDIR/qmail-$SERVICE || exit 1
	svok $SVDIR/qmail-$SERVICE/log || exit 1
        cat /var/log/qmail/$SERVICE/current $* | tai64nlocal
fi

exit 0
