#!/bin/sh
#
# svdir
# Find daemontools service directory
# Klaus Reimer <k@ailis.de>

TITLE=svdir
VERSION=0.6
AUTHOR="Klaus Reimer"
EMAIL=k@ailis.de
COPYRIGHT="Copyright (C) 2000-2011 by $AUTHOR"

showHelp() {
  echo "Usage: $TITLE [OPTION]..."
  echo "Find daemontools service directory"
  echo ""
  echo "  -h, --help     Display help and exit"
  echo "  -V, --version  Display version and exit"
  echo ""
  echo "This utility tries to find the daemontools service directory and"
  echo "print it to stdout. It first checks the current directory of a"
  echo "running svscan process and then it checks some default locations"
  echo "like /var/lib/svscan and /service. It returns 0 if it have found"
  echo "the location and 1 if not."
  echo ""
  echo "Report bugs to $AUTHOR <$EMAIL>"
}

showVersion() {
  echo "$TITLE $VERSION"
  echo ""
  echo "$COPYRIGHT"
  echo "This is free software; you can redistribute it and/or modify it under"
  echo "the terms of the GNU General Public License as published by the Free"
  echo "Software Foundation; either version 2 of the License, or (at your"
  echo "option) any later version."
}

while getopts "hV-:" NAME
do
  case "$NAME" in
    h)
      showHelp
      exit 0
      ;;
    V)
      showVersion
      exit 0
      ;;
    -)
      case "$OPTARG" in
        help)
          showHelp
          exit 0
          ;;
        version)
          showVersion
          exit 0
          ;;
        *)
          echo "Unknown option: $OPTARG"
          showHelp
          exit 1
      esac  
      ;;
    *)
      echo "Unknown option: $OPTARG"
      showHelp
      exit 1
  esac
done

shift `expr $OPTIND - 1`
if [ $# -ne 0 ]
then
  showHelp
  exit 1
fi

if ! SVDIR=`readlink /proc/\`pidof svscan\`/cwd`
then
  if [ -d "/var/lib/svscan" ]
  then
    SVDIR="/var/lib/svscan"
  else
    if [ -d "/service" ]
    then
      SVDIR="/service"
    else
      echo "$TITLE: Unable to determine daemontools service dir" >&2
      exit 1
    fi
  fi
fi

echo "$SVDIR"
exit 0
