#!/bin/sh

QMAILDIR=$(getent passwd qmaild | cut -d: -f6)
VPOPMAILUID=`id -u vpopmail`
VPOPMAILGID=`id -g vpopmail`
HOSTNAME=`cat $QMAILDIR/control/me`

exec /usr/local/bin/tcpserver -l 0 -R -H -v \
	-u "$VPOPMAILUID" -g "$VPOPMAILGID" 0 110 \
	$QMAILDIR/bin/qmail-popup $HOSTNAME \
	~vpopmail/bin/vchkpw \
	$QMAILDIR/bin/qmail-pop3d Maildir 2>&1
